
export const breadcrumbMapping = {
    // หน้าเว็บทั้งหมด
    "/": "หน้าหลัก",
    "/webboard": "กระทู้ทั้งหมด",
    "/webboard/category": "หมวดหมู่", 
    "/news": "ข่าวประชาสัมพันธ์",
    "/newsDetail": "รายละเอียดข่าวประชาสัมพันธ์",
    "/activity": "กิจกรรม",
    "/about": "เกี่ยวกับสมาคม",
    "/alumni": "ทำเนียบศิษย์เก่า",
    "/dashboard-stat": "แดชบอร์ด",
    // "/category/:categoryId": "หมวดหมู่",
    "/souvenir": "ของที่ระลึก",
    "/donate": "บริจาค",
    "/donate/donatedetail": "รายละเอียดการบริจาค",
    "/souvenir/souvenirDetail": "รายละเอียดสินค้า",
    "/souvenir/souvenir_basket": "ตะกร้าสินค้า",
    "/faq": "คำถามที่พบบ่อย",
    "/souvenir/souvenir_request" : "เพิ่มสินค้าของที่ระลึก",
    "/donate/donaterequest": "เพิ่มโครงการบริจาค",
    "/alumni/major-detail" : "รายชื่อศิษย์เก่า",
    "/news/edit" : "แก้ไขข่าวประชาสัมพันธ์",
    "/activity/edit" : "แก้ไขกิจกรรม",
    "/change-password" : "เปลี่ยนรหัสผ่านครั้งแรก",
    "/souvenir/checkout" : "ชำระเงิน",
    "/check-fullName": "ตรวจสอบข้อมูล",
    "/search": "ผลการค้นหา",
    "/donate/donatedetail/donateconfirm": "ยืนยันข้อมูลการบริจาค",
    "/dashboard-activity": "กิจกรรมที่กำลังดำเนินการ",
    "/dashboard-participants": "จำนวนผู้เข้าร่วมกิจกรรมทั้งหมด",
    "/dashboard-donation": "ยอดบริจาคทั้งหมด",
    "/dashboard-project": "โครงการที่เปิดรับบริจาค",
    "/dashboard-alumni": "รายชื่อศิษย์เก่าทั้งหมด",
    "/donate/donate-general": "บริจาคทั่วไป",
    "/donate/donation-summary-detail": "ยอดบริจาคโครงการ",
    "/donate/donation-summary-detail/project": "ยอดบริจาคโครงการ",
    "/donate/donation-summary-detail/general": "ยอดบริจาคทั่วไป",
    "/donate/donation-summary-detail/all": "ยอดบริจาครวมทั้งหมด",

    // ส่วนของศิษย์เก่า
    "/alumni-profile": "โปรไฟล์",
    "/alumni-home": "หน้าหลักศิษย์เก่า",
    "/alumni-profile/alumni-profile-webboard": "กระทู้ที่สร้าง",
    "/alumni-favorite": "กระทู้ที่กดใจ",
    "/alumni-profile/alumni-profile-webboard/edit-webboard": "แก้ไขกระทู้ที่สร้าง",
    "/createPost": "สร้างกระทู้ใหม่", 
    "/alumni-profile/alumni-profile-activity": "ประวัติการเข้าร่วมกิจกรรม",
    "/alumni-profile/alumni-request": "รายการคำร้องที่รออนุมัติ",
    "/alumni-profile/alumni-profile-souvenir": "ประวัติการสั่งซื้อของที่ระลึก",
    "/alumni-profile/alumni-profile-donation": "ประวัติการบริจาค",
    "/alumni-profile/alumni-manage-orders": "จัดการคำสั่งซื้อของที่ระลึก",
    "/alumni/major-detail/cs" : "สาขาวิทยาการคอมพิวเตอร์",
    "/alumni/major-detail/it" : "สาขาเทคโนโลยีสารสนเทศ",
    "/alumni/major-detail/gis" : "สาขาภูมิสารสนเทศศาสตร์",
    "/alumni/major-detail/cy" : "สาขาความปลอดภัยไซเบอร์",
    "/alumni/major-detail/ai" : "สาขาปัญญาประดิษฐ์",
    
    // ส่วนศิษย์ปัจุบัน
    "/student-profile": "โปรไฟล์",
    "/student-profile/student-profile-webboard": "กระทู้ที่สร้าง",
    "/student-profile/student-profile-webboard/edit-webboard": "แก้ไขกระทู้ที่สร้าง",
    "/student-profile/student-profile-activity": "ประวัติการเข้าร่วมกิจกรรม",
    "/student-profile/student-profile-souvenir": "ประวัติการสั่งซื้อของที่ระลึก",
    "/student-profile/student-request": "รายการคำร้องที่รออนุมัติ",
    "/student-profile/student-profile-donation": "ประวัติการบริจาค",
    "/student-profile/student-manage-orders": "จัดการคำสั่งซื้อของที่ระลึก",
    // "/student-profile/student-profile-souvenir/student-orders-history": "ประวัติการสั่งซื้อของที่ระลึก",
    
    // นายกสมาคม
    "/president-profile": "โปรไฟล์",
    "/president-profile/president-profile-activity": "ประวัติการเข้าร่วมกิจกรรม",
    "/president-profile/president-profile-souvenir": "การซื้อของที่ระลึก",
    "/president-profile/president-profile-webboard": "กระทู้ที่สร้าง",
    "/president-profile/president-profile-webboard/edit-webboard": "แก้ไขกระทู้ที่สร้าง",
    "/president-profile/president-approve": "การอนุมัติ",
    "/activity/president-create-activity": "เพิ่มกิจกรรม",
    "/news/president-create-news": "เพิ่มข่าวประชาสัมพันธ์",
    "/president-profile/president-profile-donation": "ประวัติการบริจาค",
    "/president-profile/president-manage-orders": "จัดการคำสั่งซื้อของที่ระลึก",

  };